version: "3.9"
services:
  web:
    build: .
    image: g00376755/emergingtech
    ports:
      - "8888:8888"
    volumes:
      - .:/home/joyvan/repo
    environment:
      JUPYTER_ENABLE_LAB: yes
      GRANT_SUDO: yes